import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'tw-elements'
export default function Home() {
  return (
    <>
    
    <div>
      <Head>
        <title>ShoeMart.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div
  id="carouselExampleCrossfade"
  className="carousel slide carousel-fade relative"
  data-bs-ride="carousel"
>
  <div className="carousel-indicators absolute right-0 bottom-0 left-0 flex justify-center p-0 mb-4">
    <button
      type="button"
      data-bs-target="#carouselExampleCrossfade"
      data-bs-slide-to="0"
      className="active"
      aria-current="true"
      aria-label="Slide 1"
    ></button>
    <button
      type="button"
      data-bs-target="#carouselExampleCrossfade"
      data-bs-slide-to="1"
      aria-label="Slide 2"
    ></button>
    <button
      type="button"
      data-bs-target="#carouselExampleCrossfade"
      data-bs-slide-to="2"
      aria-label="Slide 3"
    ></button>
  </div>
  <div className="carousel-inner relative w-full overflow-hidden">
    <div className="carousel-item active float-left w-full">
      <img
        src="https://mdbcdn.b-cdn.net/img/new/slides/041.webp"
        className="block w-full"
        alt="Wild Landscape"
      />
    </div>
    <div className="carousel-item float-left w-full">
      <img
        src="https://mdbcdn.b-cdn.net/img/new/slides/042.webp"
        className="block w-full"
        alt="Camera"
      />
    </div>
    <div className="carousel-item float-left w-full">
      <img
        src="https://mdbcdn.b-cdn.net/img/new/slides/043.webp"
        className="block w-full"
        alt="Exotic Fruits"
      />
    </div>
  </div>
  <button
    className="carousel-control-prev absolute top-0 bottom-0 flex items-center justify-center p-0 text-center border-0 hover:outline-none hover:no-underline focus:outline-none focus:no-underline left-0"
    type="button"
    data-bs-target="#carouselExampleCrossfade"
    data-bs-slide="prev"
  >
    <span className="carousel-control-prev-icon inline-block bg-no-repeat" aria-hidden="true"></span>
    <span className="visually-hidden">Previous</span>
  </button>
  <button
    className="carousel-control-next absolute top-0 bottom-0 flex items-center justify-center p-0 text-center border-0 hover:outline-none hover:no-underline focus:outline-none focus:no-underline right-0"
    type="button"
    data-bs-target="#carouselExampleCrossfade"
    data-bs-slide="next"
  >
    <span className="carousel-control-next-icon inline-block bg-no-repeat" aria-hidden="true"></span>
    <span className="visually-hidden">Next</span>
  </button>
</div>

      <section className="text-gray-600 body-font">
        <div className="container px-5 py-24 mx-auto">
          <div className="flex flex-wrap w-full mb-20 flex-col items-center text-center">
            <h1 className="sm:text-4xl text-2xl font-bold title-font mb-2 text-gray-900">
             ShoeMart.com
            </h1>
            <p className="lg:w-1/2 w-full leading-relaxed text-gray-500">
            A shoe is an item of footwear intended to protect and comfort the human foot. They are often worn with a sock. Shoes are also used as an item of decoration and fashion.
            </p>
          </div>
          <div className="flex flex-wrap -m-4">
            <div className="xl:w-1/3 md:w-1/2 p-4">
              <div className="border border-gray-200 p-6 rounded-lg">
                <div className="w-30 h-15 inline-flex items-center justify-center rounded-full bg-pink-100 text-pink-500 mb-4">
                  <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Kinderschoenen.jpg/1200px-Kinderschoenen.jpg" alt="" />
                </div>
                <h2 className="text-lg text-gray-900 font-medium title-font mb-2">
                  Blue Sneakers
                </h2>
                <p className="leading-relaxed text-base">
                There are many different types of shoes. Athletic shoes, for example, are lightweight to make running, walking or jogging easier. The sole of the shoe is also softer. Shoes for formal wear are made of leather. They are worn for business and ceremonial functions. They are also worn for fashion. Slippers are a kind of indoor shoe. They are often worn when it is cold. Shoes with a high heel are called high heels. Tall shoes are boots. Rubber boots are used in wet places.
                </p>
              </div>
            </div>
            <div className="xl:w-1/3 md:w-1/2 p-4">
              <div className="border border-gray-200 p-6 rounded-lg ">
                <div className="w-30 h-15 inline-flex items-center justify-center rounded-full bg-pink-100 text-pink-500 mb-4">
                  <img src="https://cdn.shopify.com/s/files/1/0023/9724/1443/files/hm-mto-img_f3438769-3046-4c72-beab-6250997bba0a_1600x.jpg?v=1622451951" alt="" />
                </div>
                <h2 className="text-lg text-gray-900 font-medium title-font mb-2">
                 
                 Gentle Curves
                </h2>
                <p className="leading-relaxed text-base py-10">
                At CNES Shoemaker, we strive to create elegant and functional items to suit your needs. By merging classical construction with timeless sensibility, we hope to empower discerning individual with fine shoes. Our mission is simple, we want to create good shoes and showcase exquisite craftsmanship to the world.
                </p>
              </div>
            </div>
            <div className="xl:w-1/3 md:w-1/2 p-4">
              <div className="border border-gray-200 p-6 rounded-lg">
                <div className="w-30 h-15 inline-flex items-center justify-center rounded-full bg-pink-100 text-pink-500 mb-4">
                  <img src="https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto,fl_lossy,c_fill,g_auto/832f926ac5b740589dedaf3f00ebd809_9366/avryn-shoes.jpg" alt="" />
                </div>
                <h2 className="text-lg text-gray-900 font-medium title-font mb-2">
                 Web BOOST Shoes
                </h2>
                <p className="leading-relaxed text-base">
                A shoe is an item of footwear intended to protect and comfort the human foot. They are often worn with a sock. Shoes are also used as an item of decoration and fashion. The design of shoes has varied enormously through time and from culture to culture, with form originally being tied to function.
                </p>
              </div>
            </div>
           
            
            
          </div>
          
        </div>
      </section>
    </div>
  

    </>
    
   
  )
}
